// Code generated by protoc-gen-go. DO NOT EDIT.
// source: matias_client.proto

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MatiasClientAcceptedState int32

const (
	MatiasClientAcceptedState_EMPTY    MatiasClientAcceptedState = 0
	MatiasClientAcceptedState_ACEPTED  MatiasClientAcceptedState = 1
	MatiasClientAcceptedState_DECLINED MatiasClientAcceptedState = 2
)

var MatiasClientAcceptedState_name = map[int32]string{
	0: "EMPTY",
	1: "ACEPTED",
	2: "DECLINED",
}
var MatiasClientAcceptedState_value = map[string]int32{
	"EMPTY":    0,
	"ACEPTED":  1,
	"DECLINED": 2,
}

func (x MatiasClientAcceptedState) String() string {
	return proto.EnumName(MatiasClientAcceptedState_name, int32(x))
}
func (MatiasClientAcceptedState) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type MatiasClient struct {
	Id        uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	HostName  string `protobuf:"bytes,3,opt,name=hostName" json:"hostName,omitempty"`
	Key       string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	Accepted  bool   `protobuf:"varint,5,opt,name=accepted" json:"accepted,omitempty"`
	Connected bool   `protobuf:"varint,6,opt,name=connected" json:"connected,omitempty"`
}

func (m *MatiasClient) Reset()                    { *m = MatiasClient{} }
func (m *MatiasClient) String() string            { return proto.CompactTextString(m) }
func (*MatiasClient) ProtoMessage()               {}
func (*MatiasClient) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *MatiasClient) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatiasClient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MatiasClient) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *MatiasClient) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MatiasClient) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *MatiasClient) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

type SearchMatiasClientsRequest struct {
}

func (m *SearchMatiasClientsRequest) Reset()                    { *m = SearchMatiasClientsRequest{} }
func (m *SearchMatiasClientsRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchMatiasClientsRequest) ProtoMessage()               {}
func (*SearchMatiasClientsRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

type SearchMatiasClientsResponse struct {
	MatiasClients    []*MatiasClient `protobuf:"bytes,1,rep,name=matiasClients" json:"matiasClients,omitempty"`
	MaxMatiasClients uint32          `protobuf:"varint,2,opt,name=maxMatiasClients" json:"maxMatiasClients,omitempty"`
}

func (m *SearchMatiasClientsResponse) Reset()                    { *m = SearchMatiasClientsResponse{} }
func (m *SearchMatiasClientsResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchMatiasClientsResponse) ProtoMessage()               {}
func (*SearchMatiasClientsResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *SearchMatiasClientsResponse) GetMatiasClients() []*MatiasClient {
	if m != nil {
		return m.MatiasClients
	}
	return nil
}

func (m *SearchMatiasClientsResponse) GetMaxMatiasClients() uint32 {
	if m != nil {
		return m.MaxMatiasClients
	}
	return 0
}

type FetchMatiasClientRequest struct {
	MatiasClientIds []uint32 `protobuf:"varint,1,rep,packed,name=matiasClientIds" json:"matiasClientIds,omitempty"`
}

func (m *FetchMatiasClientRequest) Reset()                    { *m = FetchMatiasClientRequest{} }
func (m *FetchMatiasClientRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchMatiasClientRequest) ProtoMessage()               {}
func (*FetchMatiasClientRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *FetchMatiasClientRequest) GetMatiasClientIds() []uint32 {
	if m != nil {
		return m.MatiasClientIds
	}
	return nil
}

type FetchMatiasClientResponse struct {
	MatiasClients []*MatiasClient `protobuf:"bytes,1,rep,name=matiasClients" json:"matiasClients,omitempty"`
}

func (m *FetchMatiasClientResponse) Reset()                    { *m = FetchMatiasClientResponse{} }
func (m *FetchMatiasClientResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchMatiasClientResponse) ProtoMessage()               {}
func (*FetchMatiasClientResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *FetchMatiasClientResponse) GetMatiasClients() []*MatiasClient {
	if m != nil {
		return m.MatiasClients
	}
	return nil
}

type FetchMatiasClientEwDatabasesRequest struct {
	MatiasClientIds []uint32 `protobuf:"varint,1,rep,packed,name=matiasClientIds" json:"matiasClientIds,omitempty"`
}

func (m *FetchMatiasClientEwDatabasesRequest) Reset()         { *m = FetchMatiasClientEwDatabasesRequest{} }
func (m *FetchMatiasClientEwDatabasesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchMatiasClientEwDatabasesRequest) ProtoMessage()    {}
func (*FetchMatiasClientEwDatabasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{5}
}

func (m *FetchMatiasClientEwDatabasesRequest) GetMatiasClientIds() []uint32 {
	if m != nil {
		return m.MatiasClientIds
	}
	return nil
}

type FetchMatiasClientEwDatabasesResponse struct {
	EwDatabases map[uint32]*FetchMatiasClientEwDatabasesResponse_EwDatabases `protobuf:"bytes,1,rep,name=ewDatabases" json:"ewDatabases,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FetchMatiasClientEwDatabasesResponse) Reset()         { *m = FetchMatiasClientEwDatabasesResponse{} }
func (m *FetchMatiasClientEwDatabasesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchMatiasClientEwDatabasesResponse) ProtoMessage()    {}
func (*FetchMatiasClientEwDatabasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{6}
}

func (m *FetchMatiasClientEwDatabasesResponse) GetEwDatabases() map[uint32]*FetchMatiasClientEwDatabasesResponse_EwDatabases {
	if m != nil {
		return m.EwDatabases
	}
	return nil
}

type FetchMatiasClientEwDatabasesResponse_EwDatabases struct {
	EwDatabases []*EwDatabase `protobuf:"bytes,1,rep,name=ewDatabases" json:"ewDatabases,omitempty"`
}

func (m *FetchMatiasClientEwDatabasesResponse_EwDatabases) Reset() {
	*m = FetchMatiasClientEwDatabasesResponse_EwDatabases{}
}
func (m *FetchMatiasClientEwDatabasesResponse_EwDatabases) String() string {
	return proto.CompactTextString(m)
}
func (*FetchMatiasClientEwDatabasesResponse_EwDatabases) ProtoMessage() {}
func (*FetchMatiasClientEwDatabasesResponse_EwDatabases) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{6, 0}
}

func (m *FetchMatiasClientEwDatabasesResponse_EwDatabases) GetEwDatabases() []*EwDatabase {
	if m != nil {
		return m.EwDatabases
	}
	return nil
}

type UpdateMatiasClientRequest struct {
	MatiasClientId uint32                    `protobuf:"varint,1,opt,name=matiasClientId" json:"matiasClientId,omitempty"`
	State          MatiasClientAcceptedState `protobuf:"varint,2,opt,name=state,enum=SeppoService.MatiasClientAcceptedState" json:"state,omitempty"`
	Name           string                    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *UpdateMatiasClientRequest) Reset()                    { *m = UpdateMatiasClientRequest{} }
func (m *UpdateMatiasClientRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMatiasClientRequest) ProtoMessage()               {}
func (*UpdateMatiasClientRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *UpdateMatiasClientRequest) GetMatiasClientId() uint32 {
	if m != nil {
		return m.MatiasClientId
	}
	return 0
}

func (m *UpdateMatiasClientRequest) GetState() MatiasClientAcceptedState {
	if m != nil {
		return m.State
	}
	return MatiasClientAcceptedState_EMPTY
}

func (m *UpdateMatiasClientRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateMatiasClientResponse struct {
	Success      bool          `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	MatiasClient *MatiasClient `protobuf:"bytes,2,opt,name=matiasClient" json:"matiasClient,omitempty"`
}

func (m *UpdateMatiasClientResponse) Reset()                    { *m = UpdateMatiasClientResponse{} }
func (m *UpdateMatiasClientResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMatiasClientResponse) ProtoMessage()               {}
func (*UpdateMatiasClientResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *UpdateMatiasClientResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateMatiasClientResponse) GetMatiasClient() *MatiasClient {
	if m != nil {
		return m.MatiasClient
	}
	return nil
}

func init() {
	proto.RegisterType((*MatiasClient)(nil), "SeppoService.MatiasClient")
	proto.RegisterType((*SearchMatiasClientsRequest)(nil), "SeppoService.SearchMatiasClientsRequest")
	proto.RegisterType((*SearchMatiasClientsResponse)(nil), "SeppoService.SearchMatiasClientsResponse")
	proto.RegisterType((*FetchMatiasClientRequest)(nil), "SeppoService.FetchMatiasClientRequest")
	proto.RegisterType((*FetchMatiasClientResponse)(nil), "SeppoService.FetchMatiasClientResponse")
	proto.RegisterType((*FetchMatiasClientEwDatabasesRequest)(nil), "SeppoService.FetchMatiasClientEwDatabasesRequest")
	proto.RegisterType((*FetchMatiasClientEwDatabasesResponse)(nil), "SeppoService.FetchMatiasClientEwDatabasesResponse")
	proto.RegisterType((*FetchMatiasClientEwDatabasesResponse_EwDatabases)(nil), "SeppoService.FetchMatiasClientEwDatabasesResponse.EwDatabases")
	proto.RegisterType((*UpdateMatiasClientRequest)(nil), "SeppoService.UpdateMatiasClientRequest")
	proto.RegisterType((*UpdateMatiasClientResponse)(nil), "SeppoService.UpdateMatiasClientResponse")
	proto.RegisterEnum("SeppoService.MatiasClientAcceptedState", MatiasClientAcceptedState_name, MatiasClientAcceptedState_value)
}

func init() { proto.RegisterFile("matias_client.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x59, 0xa7, 0x69, 0x93, 0xc9, 0x1f, 0xcc, 0x72, 0x71, 0x4c, 0x0f, 0x91, 0x41, 0x60,
	0xf5, 0x90, 0x43, 0xb8, 0xa0, 0x4a, 0x54, 0x44, 0xb1, 0x91, 0x22, 0xd1, 0x52, 0x6d, 0xc2, 0x81,
	0x03, 0xaa, 0xb6, 0xf6, 0x48, 0xb5, 0x68, 0x6c, 0x93, 0xdd, 0xa4, 0xf4, 0xc2, 0x0b, 0x70, 0xe7,
	0xc0, 0x93, 0xf1, 0x38, 0xc8, 0x6b, 0x37, 0x59, 0xa7, 0x6e, 0x05, 0x82, 0x9b, 0xf7, 0x9b, 0x99,
	0x6f, 0x7f, 0xbb, 0x3b, 0x63, 0x78, 0x3c, 0xe7, 0x32, 0xe2, 0xe2, 0x2c, 0xb8, 0x8c, 0x30, 0x96,
	0x83, 0x74, 0x91, 0xc8, 0x84, 0xb6, 0xa7, 0x98, 0xa6, 0xc9, 0x14, 0x17, 0xab, 0x28, 0x40, 0xfb,
	0x11, 0x5e, 0x9d, 0x85, 0x5c, 0xf2, 0x73, 0x2e, 0x30, 0x4f, 0x70, 0x7e, 0x12, 0x68, 0x1f, 0xab,
	0xc2, 0xb1, 0xaa, 0xa3, 0x5d, 0x30, 0xa2, 0xd0, 0x22, 0x7d, 0xe2, 0x76, 0x98, 0x11, 0x85, 0x94,
	0xc2, 0x4e, 0xcc, 0xe7, 0x68, 0x19, 0x7d, 0xe2, 0x36, 0x99, 0xfa, 0xa6, 0x36, 0x34, 0x2e, 0x12,
	0x21, 0x4f, 0x32, 0xbd, 0xa6, 0xf4, 0xf5, 0x9a, 0x9a, 0x50, 0xfb, 0x8c, 0xd7, 0xd6, 0x8e, 0x92,
	0xb3, 0xcf, 0x2c, 0x9b, 0x07, 0x01, 0xa6, 0x12, 0x43, 0xab, 0xde, 0x27, 0x6e, 0x83, 0xad, 0xd7,
	0x74, 0x1f, 0x9a, 0x41, 0x12, 0xc7, 0x18, 0x64, 0xc1, 0x5d, 0x15, 0xdc, 0x08, 0xce, 0x3e, 0xd8,
	0x53, 0xe4, 0x8b, 0xe0, 0x42, 0x27, 0x14, 0x0c, 0xbf, 0x2c, 0x51, 0x48, 0xe7, 0x3b, 0x81, 0x27,
	0x95, 0x61, 0x91, 0x26, 0xb1, 0x40, 0xfa, 0x06, 0x3a, 0x73, 0x3d, 0x60, 0x91, 0x7e, 0xcd, 0x6d,
	0x0d, 0xed, 0x81, 0x7e, 0x27, 0x03, 0xbd, 0x96, 0x95, 0x0b, 0xe8, 0x01, 0x98, 0x73, 0xfe, 0xb5,
	0xe4, 0xae, 0xee, 0xa1, 0xc3, 0x6e, 0xe9, 0x8e, 0x07, 0xd6, 0x5b, 0x94, 0x65, 0x96, 0x82, 0x94,
	0xba, 0xf0, 0x50, 0x37, 0x9e, 0x84, 0x39, 0x4b, 0x87, 0x6d, 0xcb, 0xce, 0x27, 0xe8, 0x55, 0xb8,
	0xfc, 0xaf, 0x03, 0x39, 0xef, 0xe1, 0xe9, 0x2d, 0x7b, 0xff, 0xca, 0x2b, 0x5a, 0x42, 0xfc, 0x3d,
	0xef, 0x2f, 0x03, 0x9e, 0xdd, 0xef, 0x58, 0xb0, 0x23, 0xb4, 0x70, 0x23, 0x17, 0xe4, 0xe3, 0x32,
	0xf9, 0x9f, 0x18, 0x0d, 0x34, 0xcd, 0x8f, 0xe5, 0xe2, 0x9a, 0xe9, 0xbe, 0xf6, 0x04, 0x5a, 0x5a,
	0x02, 0x3d, 0xac, 0xda, 0xd5, 0x2a, 0xef, 0xba, 0xc9, 0x2f, 0x5b, 0x7d, 0x03, 0x73, 0x7b, 0xaf,
	0x9b, 0xe6, 0xce, 0xa7, 0x43, 0x35, 0xf7, 0x0c, 0xea, 0x2b, 0x7e, 0xb9, 0xcc, 0xe7, 0xa3, 0x35,
	0x3c, 0xfa, 0xb7, 0x13, 0xb1, 0xdc, 0xec, 0xd0, 0x78, 0x45, 0x9c, 0x1f, 0x04, 0x7a, 0x1f, 0xd2,
	0x90, 0x4b, 0xac, 0x6a, 0xa9, 0xe7, 0xd0, 0x2d, 0xbf, 0x45, 0x01, 0xb5, 0xa5, 0xd2, 0xd7, 0x50,
	0x17, 0x92, 0xcb, 0x9c, 0xaf, 0x3b, 0x7c, 0x71, 0x77, 0xaf, 0x8c, 0x8a, 0x99, 0x9c, 0x66, 0xe9,
	0x2c, 0xaf, 0x5a, 0x4f, 0x7f, 0x6d, 0x33, 0xfd, 0xce, 0x0a, 0xec, 0x2a, 0xae, 0xe2, 0xa1, 0x2d,
	0xd8, 0x13, 0xcb, 0x20, 0x40, 0x21, 0x14, 0x51, 0x83, 0xdd, 0x2c, 0xe9, 0x11, 0xb4, 0x75, 0xb8,
	0xe2, 0xc6, 0xee, 0xeb, 0xde, 0x52, 0xfe, 0xc1, 0x08, 0x7a, 0x77, 0xf2, 0xd2, 0x26, 0xd4, 0xfd,
	0xe3, 0xd3, 0xd9, 0x47, 0xf3, 0x01, 0x6d, 0xc1, 0xde, 0x68, 0xec, 0x9f, 0xce, 0x7c, 0xcf, 0x24,
	0xb4, 0x0d, 0x0d, 0xcf, 0x1f, 0xbf, 0x9b, 0x9c, 0xf8, 0x9e, 0x69, 0x9c, 0xef, 0xaa, 0x9f, 0xde,
	0xcb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0x65, 0xfe, 0xe2, 0x2c, 0x05, 0x00, 0x00,
}
