// Code generated by protoc-gen-go. DO NOT EDIT.
// source: seppo_service.proto

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Seppo service

type SeppoClient interface {
	FetchVariationById(ctx context.Context, in *FetchVariationByIdRequest, opts ...grpc.CallOption) (*FetchVariationByIdResponse, error)
	SearchVariations(ctx context.Context, in *SearchVariationsRequest, opts ...grpc.CallOption) (*SearchVariationsResponse, error)
	FetchNewestVariationVersionByVariationId(ctx context.Context, in *FetchNewestVariationVersionByVariationIdRequest, opts ...grpc.CallOption) (*FetchNewestVariationVersionByVariationIdResponse, error)
	FetchVariationVersionById(ctx context.Context, in *FetchVariationVersionByIdRequest, opts ...grpc.CallOption) (*FetchVariationVersionByIdResponse, error)
	SearchSongDatabases(ctx context.Context, in *SearchSongDatabasesRequest, opts ...grpc.CallOption) (*SearchSongDatabasesResponse, error)
	FetchSongDatabaseById(ctx context.Context, in *FetchSongDatabaseByIdRequest, opts ...grpc.CallOption) (*FetchSongDatabaseByIdResponse, error)
	SearchEwDatabases(ctx context.Context, in *SearchEwDatabasesRequest, opts ...grpc.CallOption) (*SearchEwDatabasesResponse, error)
	FetchEwDatabaseById(ctx context.Context, in *FetchEwDatabaseByIdRequest, opts ...grpc.CallOption) (*FetchEwDatabaseByIdResponse, error)
	SearchTags(ctx context.Context, in *SearchTagsRequest, opts ...grpc.CallOption) (*SearchTagsResponse, error)
	FetchTagById(ctx context.Context, in *FetchTagByIdRequest, opts ...grpc.CallOption) (*FetchTagByIdResponse, error)
	SearchLanguages(ctx context.Context, in *SearchLanguagesRequest, opts ...grpc.CallOption) (*SearchLanguagesResponse, error)
	FetchLanguageById(ctx context.Context, in *FetchLanguageByIdRequest, opts ...grpc.CallOption) (*FetchLanguageByIdResponse, error)
	SearchSchedules(ctx context.Context, in *SearchSchedulesRequest, opts ...grpc.CallOption) (*SearchSchedulesResponse, error)
	FetchScheduleById(ctx context.Context, in *FetchScheduleByIdRequest, opts ...grpc.CallOption) (*FetchScheduleByIdResponse, error)
	SearchAuthors(ctx context.Context, in *SearchAuthorsRequest, opts ...grpc.CallOption) (*SearchAuthorsResponse, error)
	FetchAuthorById(ctx context.Context, in *FetchAuthorByIdRequest, opts ...grpc.CallOption) (*FetchAuthorByIdResponse, error)
	SearchCopyrights(ctx context.Context, in *SearchCopyrightsRequest, opts ...grpc.CallOption) (*SearchCopyrightsResponse, error)
	FetchCopyrightById(ctx context.Context, in *FetchCopyrightByIdRequest, opts ...grpc.CallOption) (*FetchCopyrightByIdResponse, error)
	SearchMatiasClients(ctx context.Context, in *SearchMatiasClientsRequest, opts ...grpc.CallOption) (*SearchMatiasClientsResponse, error)
	FetchMatiasClient(ctx context.Context, in *FetchMatiasClientRequest, opts ...grpc.CallOption) (*FetchMatiasClientResponse, error)
	FetchMatiasClientEwDatabases(ctx context.Context, in *FetchMatiasClientEwDatabasesRequest, opts ...grpc.CallOption) (*FetchMatiasClientEwDatabasesResponse, error)
	SearchLogs(ctx context.Context, in *SearchLogsRequest, opts ...grpc.CallOption) (*SearchLogsResponse, error)
	CreateVariation(ctx context.Context, in *CreateVariationRequest, opts ...grpc.CallOption) (*CreateVariationResponse, error)
	UpdateVariation(ctx context.Context, in *UpdateVariationRequest, opts ...grpc.CallOption) (*UpdateVariationResponse, error)
	RemoveVariation(ctx context.Context, in *RemoveVariationRequest, opts ...grpc.CallOption) (*RemoveVariationResponse, error)
	CreateSongDatabase(ctx context.Context, in *CreateSongDatabaseRequest, opts ...grpc.CallOption) (*CreateSongDatabaseResponse, error)
	UpdateSongDatabase(ctx context.Context, in *UpdateSongDatabaseRequest, opts ...grpc.CallOption) (*UpdateSongDatabaseResponse, error)
	RemoveSongDatabase(ctx context.Context, in *RemoveSongDatabaseRequest, opts ...grpc.CallOption) (*RemoveSongDatabaseResponse, error)
	CreateEwDatabase(ctx context.Context, in *CreateEwDatabaseRequest, opts ...grpc.CallOption) (*CreateEwDatabaseResponse, error)
	UpdateEwDatabase(ctx context.Context, in *UpdateEwDatabaseRequest, opts ...grpc.CallOption) (*UpdateEwDatabaseResponse, error)
	RemoveEwDatabase(ctx context.Context, in *RemoveEwDatabaseRequest, opts ...grpc.CallOption) (*RemoveEwDatabaseResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
	RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*RemoveTagResponse, error)
	CreateLanguage(ctx context.Context, in *CreateLanguageRequest, opts ...grpc.CallOption) (*CreateLanguageResponse, error)
	UpdateLanguage(ctx context.Context, in *UpdateLanguageRequest, opts ...grpc.CallOption) (*UpdateLanguageResponse, error)
	RemoveLanguage(ctx context.Context, in *RemoveLanguageRequest, opts ...grpc.CallOption) (*RemoveLanguageResponse, error)
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error)
	UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*UpdateScheduleResponse, error)
	RemoveSchedule(ctx context.Context, in *RemoveScheduleRequest, opts ...grpc.CallOption) (*RemoveScheduleResponse, error)
	CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*CreateAuthorResponse, error)
	UpdateAuthor(ctx context.Context, in *UpdateAuthorRequest, opts ...grpc.CallOption) (*UpdateAuthorResponse, error)
	RemoveAuthor(ctx context.Context, in *RemoveAuthorRequest, opts ...grpc.CallOption) (*RemoveAuthorResponse, error)
	CreateCopyright(ctx context.Context, in *CreateCopyrightRequest, opts ...grpc.CallOption) (*CreateCopyrightResponse, error)
	UpdateCopyright(ctx context.Context, in *UpdateCopyrightRequest, opts ...grpc.CallOption) (*UpdateCopyrightResponse, error)
	RemoveCopyright(ctx context.Context, in *RemoveCopyrightRequest, opts ...grpc.CallOption) (*RemoveCopyrightResponse, error)
	UpdateMatiasClient(ctx context.Context, in *UpdateMatiasClientRequest, opts ...grpc.CallOption) (*UpdateMatiasClientResponse, error)
}

type seppoClient struct {
	cc *grpc.ClientConn
}

func NewSeppoClient(cc *grpc.ClientConn) SeppoClient {
	return &seppoClient{cc}
}

func (c *seppoClient) FetchVariationById(ctx context.Context, in *FetchVariationByIdRequest, opts ...grpc.CallOption) (*FetchVariationByIdResponse, error) {
	out := new(FetchVariationByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchVariationById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchVariations(ctx context.Context, in *SearchVariationsRequest, opts ...grpc.CallOption) (*SearchVariationsResponse, error) {
	out := new(SearchVariationsResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchVariations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchNewestVariationVersionByVariationId(ctx context.Context, in *FetchNewestVariationVersionByVariationIdRequest, opts ...grpc.CallOption) (*FetchNewestVariationVersionByVariationIdResponse, error) {
	out := new(FetchNewestVariationVersionByVariationIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchNewestVariationVersionByVariationId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchVariationVersionById(ctx context.Context, in *FetchVariationVersionByIdRequest, opts ...grpc.CallOption) (*FetchVariationVersionByIdResponse, error) {
	out := new(FetchVariationVersionByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchVariationVersionById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchSongDatabases(ctx context.Context, in *SearchSongDatabasesRequest, opts ...grpc.CallOption) (*SearchSongDatabasesResponse, error) {
	out := new(SearchSongDatabasesResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchSongDatabases", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchSongDatabaseById(ctx context.Context, in *FetchSongDatabaseByIdRequest, opts ...grpc.CallOption) (*FetchSongDatabaseByIdResponse, error) {
	out := new(FetchSongDatabaseByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchSongDatabaseById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchEwDatabases(ctx context.Context, in *SearchEwDatabasesRequest, opts ...grpc.CallOption) (*SearchEwDatabasesResponse, error) {
	out := new(SearchEwDatabasesResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchEwDatabases", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchEwDatabaseById(ctx context.Context, in *FetchEwDatabaseByIdRequest, opts ...grpc.CallOption) (*FetchEwDatabaseByIdResponse, error) {
	out := new(FetchEwDatabaseByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchEwDatabaseById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchTags(ctx context.Context, in *SearchTagsRequest, opts ...grpc.CallOption) (*SearchTagsResponse, error) {
	out := new(SearchTagsResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchTags", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchTagById(ctx context.Context, in *FetchTagByIdRequest, opts ...grpc.CallOption) (*FetchTagByIdResponse, error) {
	out := new(FetchTagByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchTagById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchLanguages(ctx context.Context, in *SearchLanguagesRequest, opts ...grpc.CallOption) (*SearchLanguagesResponse, error) {
	out := new(SearchLanguagesResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchLanguages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchLanguageById(ctx context.Context, in *FetchLanguageByIdRequest, opts ...grpc.CallOption) (*FetchLanguageByIdResponse, error) {
	out := new(FetchLanguageByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchLanguageById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchSchedules(ctx context.Context, in *SearchSchedulesRequest, opts ...grpc.CallOption) (*SearchSchedulesResponse, error) {
	out := new(SearchSchedulesResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchSchedules", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchScheduleById(ctx context.Context, in *FetchScheduleByIdRequest, opts ...grpc.CallOption) (*FetchScheduleByIdResponse, error) {
	out := new(FetchScheduleByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchScheduleById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchAuthors(ctx context.Context, in *SearchAuthorsRequest, opts ...grpc.CallOption) (*SearchAuthorsResponse, error) {
	out := new(SearchAuthorsResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchAuthors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchAuthorById(ctx context.Context, in *FetchAuthorByIdRequest, opts ...grpc.CallOption) (*FetchAuthorByIdResponse, error) {
	out := new(FetchAuthorByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchAuthorById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchCopyrights(ctx context.Context, in *SearchCopyrightsRequest, opts ...grpc.CallOption) (*SearchCopyrightsResponse, error) {
	out := new(SearchCopyrightsResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchCopyrights", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchCopyrightById(ctx context.Context, in *FetchCopyrightByIdRequest, opts ...grpc.CallOption) (*FetchCopyrightByIdResponse, error) {
	out := new(FetchCopyrightByIdResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchCopyrightById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchMatiasClients(ctx context.Context, in *SearchMatiasClientsRequest, opts ...grpc.CallOption) (*SearchMatiasClientsResponse, error) {
	out := new(SearchMatiasClientsResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchMatiasClients", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchMatiasClient(ctx context.Context, in *FetchMatiasClientRequest, opts ...grpc.CallOption) (*FetchMatiasClientResponse, error) {
	out := new(FetchMatiasClientResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchMatiasClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) FetchMatiasClientEwDatabases(ctx context.Context, in *FetchMatiasClientEwDatabasesRequest, opts ...grpc.CallOption) (*FetchMatiasClientEwDatabasesResponse, error) {
	out := new(FetchMatiasClientEwDatabasesResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/fetchMatiasClientEwDatabases", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) SearchLogs(ctx context.Context, in *SearchLogsRequest, opts ...grpc.CallOption) (*SearchLogsResponse, error) {
	out := new(SearchLogsResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/searchLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateVariation(ctx context.Context, in *CreateVariationRequest, opts ...grpc.CallOption) (*CreateVariationResponse, error) {
	out := new(CreateVariationResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createVariation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateVariation(ctx context.Context, in *UpdateVariationRequest, opts ...grpc.CallOption) (*UpdateVariationResponse, error) {
	out := new(UpdateVariationResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateVariation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveVariation(ctx context.Context, in *RemoveVariationRequest, opts ...grpc.CallOption) (*RemoveVariationResponse, error) {
	out := new(RemoveVariationResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeVariation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateSongDatabase(ctx context.Context, in *CreateSongDatabaseRequest, opts ...grpc.CallOption) (*CreateSongDatabaseResponse, error) {
	out := new(CreateSongDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createSongDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateSongDatabase(ctx context.Context, in *UpdateSongDatabaseRequest, opts ...grpc.CallOption) (*UpdateSongDatabaseResponse, error) {
	out := new(UpdateSongDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateSongDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveSongDatabase(ctx context.Context, in *RemoveSongDatabaseRequest, opts ...grpc.CallOption) (*RemoveSongDatabaseResponse, error) {
	out := new(RemoveSongDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeSongDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateEwDatabase(ctx context.Context, in *CreateEwDatabaseRequest, opts ...grpc.CallOption) (*CreateEwDatabaseResponse, error) {
	out := new(CreateEwDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createEwDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateEwDatabase(ctx context.Context, in *UpdateEwDatabaseRequest, opts ...grpc.CallOption) (*UpdateEwDatabaseResponse, error) {
	out := new(UpdateEwDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateEwDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveEwDatabase(ctx context.Context, in *RemoveEwDatabaseRequest, opts ...grpc.CallOption) (*RemoveEwDatabaseResponse, error) {
	out := new(RemoveEwDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeEwDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	out := new(CreateTagResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	out := new(UpdateTagResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*RemoveTagResponse, error) {
	out := new(RemoveTagResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateLanguage(ctx context.Context, in *CreateLanguageRequest, opts ...grpc.CallOption) (*CreateLanguageResponse, error) {
	out := new(CreateLanguageResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createLanguage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateLanguage(ctx context.Context, in *UpdateLanguageRequest, opts ...grpc.CallOption) (*UpdateLanguageResponse, error) {
	out := new(UpdateLanguageResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateLanguage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveLanguage(ctx context.Context, in *RemoveLanguageRequest, opts ...grpc.CallOption) (*RemoveLanguageResponse, error) {
	out := new(RemoveLanguageResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeLanguage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error) {
	out := new(CreateScheduleResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createSchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*UpdateScheduleResponse, error) {
	out := new(UpdateScheduleResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateSchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveSchedule(ctx context.Context, in *RemoveScheduleRequest, opts ...grpc.CallOption) (*RemoveScheduleResponse, error) {
	out := new(RemoveScheduleResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeSchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*CreateAuthorResponse, error) {
	out := new(CreateAuthorResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createAuthor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateAuthor(ctx context.Context, in *UpdateAuthorRequest, opts ...grpc.CallOption) (*UpdateAuthorResponse, error) {
	out := new(UpdateAuthorResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateAuthor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveAuthor(ctx context.Context, in *RemoveAuthorRequest, opts ...grpc.CallOption) (*RemoveAuthorResponse, error) {
	out := new(RemoveAuthorResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeAuthor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) CreateCopyright(ctx context.Context, in *CreateCopyrightRequest, opts ...grpc.CallOption) (*CreateCopyrightResponse, error) {
	out := new(CreateCopyrightResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/createCopyright", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateCopyright(ctx context.Context, in *UpdateCopyrightRequest, opts ...grpc.CallOption) (*UpdateCopyrightResponse, error) {
	out := new(UpdateCopyrightResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateCopyright", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) RemoveCopyright(ctx context.Context, in *RemoveCopyrightRequest, opts ...grpc.CallOption) (*RemoveCopyrightResponse, error) {
	out := new(RemoveCopyrightResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/removeCopyright", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seppoClient) UpdateMatiasClient(ctx context.Context, in *UpdateMatiasClientRequest, opts ...grpc.CallOption) (*UpdateMatiasClientResponse, error) {
	out := new(UpdateMatiasClientResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/updateMatiasClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Seppo service

type SeppoServer interface {
	FetchVariationById(context.Context, *FetchVariationByIdRequest) (*FetchVariationByIdResponse, error)
	SearchVariations(context.Context, *SearchVariationsRequest) (*SearchVariationsResponse, error)
	FetchNewestVariationVersionByVariationId(context.Context, *FetchNewestVariationVersionByVariationIdRequest) (*FetchNewestVariationVersionByVariationIdResponse, error)
	FetchVariationVersionById(context.Context, *FetchVariationVersionByIdRequest) (*FetchVariationVersionByIdResponse, error)
	SearchSongDatabases(context.Context, *SearchSongDatabasesRequest) (*SearchSongDatabasesResponse, error)
	FetchSongDatabaseById(context.Context, *FetchSongDatabaseByIdRequest) (*FetchSongDatabaseByIdResponse, error)
	SearchEwDatabases(context.Context, *SearchEwDatabasesRequest) (*SearchEwDatabasesResponse, error)
	FetchEwDatabaseById(context.Context, *FetchEwDatabaseByIdRequest) (*FetchEwDatabaseByIdResponse, error)
	SearchTags(context.Context, *SearchTagsRequest) (*SearchTagsResponse, error)
	FetchTagById(context.Context, *FetchTagByIdRequest) (*FetchTagByIdResponse, error)
	SearchLanguages(context.Context, *SearchLanguagesRequest) (*SearchLanguagesResponse, error)
	FetchLanguageById(context.Context, *FetchLanguageByIdRequest) (*FetchLanguageByIdResponse, error)
	SearchSchedules(context.Context, *SearchSchedulesRequest) (*SearchSchedulesResponse, error)
	FetchScheduleById(context.Context, *FetchScheduleByIdRequest) (*FetchScheduleByIdResponse, error)
	SearchAuthors(context.Context, *SearchAuthorsRequest) (*SearchAuthorsResponse, error)
	FetchAuthorById(context.Context, *FetchAuthorByIdRequest) (*FetchAuthorByIdResponse, error)
	SearchCopyrights(context.Context, *SearchCopyrightsRequest) (*SearchCopyrightsResponse, error)
	FetchCopyrightById(context.Context, *FetchCopyrightByIdRequest) (*FetchCopyrightByIdResponse, error)
	SearchMatiasClients(context.Context, *SearchMatiasClientsRequest) (*SearchMatiasClientsResponse, error)
	FetchMatiasClient(context.Context, *FetchMatiasClientRequest) (*FetchMatiasClientResponse, error)
	FetchMatiasClientEwDatabases(context.Context, *FetchMatiasClientEwDatabasesRequest) (*FetchMatiasClientEwDatabasesResponse, error)
	SearchLogs(context.Context, *SearchLogsRequest) (*SearchLogsResponse, error)
	CreateVariation(context.Context, *CreateVariationRequest) (*CreateVariationResponse, error)
	UpdateVariation(context.Context, *UpdateVariationRequest) (*UpdateVariationResponse, error)
	RemoveVariation(context.Context, *RemoveVariationRequest) (*RemoveVariationResponse, error)
	CreateSongDatabase(context.Context, *CreateSongDatabaseRequest) (*CreateSongDatabaseResponse, error)
	UpdateSongDatabase(context.Context, *UpdateSongDatabaseRequest) (*UpdateSongDatabaseResponse, error)
	RemoveSongDatabase(context.Context, *RemoveSongDatabaseRequest) (*RemoveSongDatabaseResponse, error)
	CreateEwDatabase(context.Context, *CreateEwDatabaseRequest) (*CreateEwDatabaseResponse, error)
	UpdateEwDatabase(context.Context, *UpdateEwDatabaseRequest) (*UpdateEwDatabaseResponse, error)
	RemoveEwDatabase(context.Context, *RemoveEwDatabaseRequest) (*RemoveEwDatabaseResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
	RemoveTag(context.Context, *RemoveTagRequest) (*RemoveTagResponse, error)
	CreateLanguage(context.Context, *CreateLanguageRequest) (*CreateLanguageResponse, error)
	UpdateLanguage(context.Context, *UpdateLanguageRequest) (*UpdateLanguageResponse, error)
	RemoveLanguage(context.Context, *RemoveLanguageRequest) (*RemoveLanguageResponse, error)
	CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error)
	UpdateSchedule(context.Context, *UpdateScheduleRequest) (*UpdateScheduleResponse, error)
	RemoveSchedule(context.Context, *RemoveScheduleRequest) (*RemoveScheduleResponse, error)
	CreateAuthor(context.Context, *CreateAuthorRequest) (*CreateAuthorResponse, error)
	UpdateAuthor(context.Context, *UpdateAuthorRequest) (*UpdateAuthorResponse, error)
	RemoveAuthor(context.Context, *RemoveAuthorRequest) (*RemoveAuthorResponse, error)
	CreateCopyright(context.Context, *CreateCopyrightRequest) (*CreateCopyrightResponse, error)
	UpdateCopyright(context.Context, *UpdateCopyrightRequest) (*UpdateCopyrightResponse, error)
	RemoveCopyright(context.Context, *RemoveCopyrightRequest) (*RemoveCopyrightResponse, error)
	UpdateMatiasClient(context.Context, *UpdateMatiasClientRequest) (*UpdateMatiasClientResponse, error)
}

func RegisterSeppoServer(s *grpc.Server, srv SeppoServer) {
	s.RegisterService(&_Seppo_serviceDesc, srv)
}

func _Seppo_FetchVariationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchVariationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchVariationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchVariationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchVariationById(ctx, req.(*FetchVariationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchVariations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVariationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchVariations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchVariations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchVariations(ctx, req.(*SearchVariationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchNewestVariationVersionByVariationId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchNewestVariationVersionByVariationIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchNewestVariationVersionByVariationId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchNewestVariationVersionByVariationId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchNewestVariationVersionByVariationId(ctx, req.(*FetchNewestVariationVersionByVariationIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchVariationVersionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchVariationVersionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchVariationVersionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchVariationVersionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchVariationVersionById(ctx, req.(*FetchVariationVersionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchSongDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSongDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchSongDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchSongDatabases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchSongDatabases(ctx, req.(*SearchSongDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchSongDatabaseById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSongDatabaseByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchSongDatabaseById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchSongDatabaseById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchSongDatabaseById(ctx, req.(*FetchSongDatabaseByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchEwDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEwDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchEwDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchEwDatabases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchEwDatabases(ctx, req.(*SearchEwDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchEwDatabaseById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchEwDatabaseByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchEwDatabaseById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchEwDatabaseById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchEwDatabaseById(ctx, req.(*FetchEwDatabaseByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchTags(ctx, req.(*SearchTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchTagById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTagByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchTagById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchTagById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchTagById(ctx, req.(*FetchTagByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchLanguages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchLanguages(ctx, req.(*SearchLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchLanguageById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchLanguageByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchLanguageById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchLanguageById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchLanguageById(ctx, req.(*FetchLanguageByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchSchedules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchSchedules(ctx, req.(*SearchSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchScheduleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchScheduleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchScheduleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchScheduleById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchScheduleById(ctx, req.(*FetchScheduleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAuthorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchAuthors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchAuthors(ctx, req.(*SearchAuthorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchAuthorById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAuthorByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchAuthorById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchAuthorById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchAuthorById(ctx, req.(*FetchAuthorByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchCopyrights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCopyrightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchCopyrights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchCopyrights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchCopyrights(ctx, req.(*SearchCopyrightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchCopyrightById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCopyrightByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchCopyrightById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchCopyrightById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchCopyrightById(ctx, req.(*FetchCopyrightByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchMatiasClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMatiasClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchMatiasClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchMatiasClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchMatiasClients(ctx, req.(*SearchMatiasClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchMatiasClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMatiasClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchMatiasClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchMatiasClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchMatiasClient(ctx, req.(*FetchMatiasClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_FetchMatiasClientEwDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMatiasClientEwDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).FetchMatiasClientEwDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/FetchMatiasClientEwDatabases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).FetchMatiasClientEwDatabases(ctx, req.(*FetchMatiasClientEwDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_SearchLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SearchLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SearchLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SearchLogs(ctx, req.(*SearchLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateVariation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVariationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateVariation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateVariation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateVariation(ctx, req.(*CreateVariationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateVariation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVariationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateVariation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateVariation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateVariation(ctx, req.(*UpdateVariationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveVariation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVariationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveVariation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveVariation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveVariation(ctx, req.(*RemoveVariationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateSongDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSongDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateSongDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateSongDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateSongDatabase(ctx, req.(*CreateSongDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateSongDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSongDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateSongDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateSongDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateSongDatabase(ctx, req.(*UpdateSongDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveSongDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSongDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveSongDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveSongDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveSongDatabase(ctx, req.(*RemoveSongDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateEwDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEwDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateEwDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateEwDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateEwDatabase(ctx, req.(*CreateEwDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateEwDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEwDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateEwDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateEwDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateEwDatabase(ctx, req.(*UpdateEwDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveEwDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEwDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveEwDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveEwDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveEwDatabase(ctx, req.(*RemoveEwDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveTag(ctx, req.(*RemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateLanguage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateLanguage(ctx, req.(*CreateLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateLanguage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateLanguage(ctx, req.(*UpdateLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveLanguage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveLanguage(ctx, req.(*RemoveLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateSchedule(ctx, req.(*UpdateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveSchedule(ctx, req.(*RemoveScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateAuthor(ctx, req.(*CreateAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateAuthor(ctx, req.(*UpdateAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveAuthor(ctx, req.(*RemoveAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_CreateCopyright_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCopyrightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).CreateCopyright(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/CreateCopyright",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).CreateCopyright(ctx, req.(*CreateCopyrightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateCopyright_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCopyrightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateCopyright(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateCopyright",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateCopyright(ctx, req.(*UpdateCopyrightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_RemoveCopyright_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCopyrightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).RemoveCopyright(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/RemoveCopyright",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).RemoveCopyright(ctx, req.(*RemoveCopyrightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seppo_UpdateMatiasClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMatiasClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).UpdateMatiasClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/UpdateMatiasClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).UpdateMatiasClient(ctx, req.(*UpdateMatiasClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Seppo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SeppoService.Seppo",
	HandlerType: (*SeppoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fetchVariationById",
			Handler:    _Seppo_FetchVariationById_Handler,
		},
		{
			MethodName: "searchVariations",
			Handler:    _Seppo_SearchVariations_Handler,
		},
		{
			MethodName: "fetchNewestVariationVersionByVariationId",
			Handler:    _Seppo_FetchNewestVariationVersionByVariationId_Handler,
		},
		{
			MethodName: "fetchVariationVersionById",
			Handler:    _Seppo_FetchVariationVersionById_Handler,
		},
		{
			MethodName: "searchSongDatabases",
			Handler:    _Seppo_SearchSongDatabases_Handler,
		},
		{
			MethodName: "fetchSongDatabaseById",
			Handler:    _Seppo_FetchSongDatabaseById_Handler,
		},
		{
			MethodName: "searchEwDatabases",
			Handler:    _Seppo_SearchEwDatabases_Handler,
		},
		{
			MethodName: "fetchEwDatabaseById",
			Handler:    _Seppo_FetchEwDatabaseById_Handler,
		},
		{
			MethodName: "searchTags",
			Handler:    _Seppo_SearchTags_Handler,
		},
		{
			MethodName: "fetchTagById",
			Handler:    _Seppo_FetchTagById_Handler,
		},
		{
			MethodName: "searchLanguages",
			Handler:    _Seppo_SearchLanguages_Handler,
		},
		{
			MethodName: "fetchLanguageById",
			Handler:    _Seppo_FetchLanguageById_Handler,
		},
		{
			MethodName: "searchSchedules",
			Handler:    _Seppo_SearchSchedules_Handler,
		},
		{
			MethodName: "fetchScheduleById",
			Handler:    _Seppo_FetchScheduleById_Handler,
		},
		{
			MethodName: "searchAuthors",
			Handler:    _Seppo_SearchAuthors_Handler,
		},
		{
			MethodName: "fetchAuthorById",
			Handler:    _Seppo_FetchAuthorById_Handler,
		},
		{
			MethodName: "searchCopyrights",
			Handler:    _Seppo_SearchCopyrights_Handler,
		},
		{
			MethodName: "fetchCopyrightById",
			Handler:    _Seppo_FetchCopyrightById_Handler,
		},
		{
			MethodName: "searchMatiasClients",
			Handler:    _Seppo_SearchMatiasClients_Handler,
		},
		{
			MethodName: "fetchMatiasClient",
			Handler:    _Seppo_FetchMatiasClient_Handler,
		},
		{
			MethodName: "fetchMatiasClientEwDatabases",
			Handler:    _Seppo_FetchMatiasClientEwDatabases_Handler,
		},
		{
			MethodName: "searchLogs",
			Handler:    _Seppo_SearchLogs_Handler,
		},
		{
			MethodName: "createVariation",
			Handler:    _Seppo_CreateVariation_Handler,
		},
		{
			MethodName: "updateVariation",
			Handler:    _Seppo_UpdateVariation_Handler,
		},
		{
			MethodName: "removeVariation",
			Handler:    _Seppo_RemoveVariation_Handler,
		},
		{
			MethodName: "createSongDatabase",
			Handler:    _Seppo_CreateSongDatabase_Handler,
		},
		{
			MethodName: "updateSongDatabase",
			Handler:    _Seppo_UpdateSongDatabase_Handler,
		},
		{
			MethodName: "removeSongDatabase",
			Handler:    _Seppo_RemoveSongDatabase_Handler,
		},
		{
			MethodName: "createEwDatabase",
			Handler:    _Seppo_CreateEwDatabase_Handler,
		},
		{
			MethodName: "updateEwDatabase",
			Handler:    _Seppo_UpdateEwDatabase_Handler,
		},
		{
			MethodName: "removeEwDatabase",
			Handler:    _Seppo_RemoveEwDatabase_Handler,
		},
		{
			MethodName: "createTag",
			Handler:    _Seppo_CreateTag_Handler,
		},
		{
			MethodName: "updateTag",
			Handler:    _Seppo_UpdateTag_Handler,
		},
		{
			MethodName: "removeTag",
			Handler:    _Seppo_RemoveTag_Handler,
		},
		{
			MethodName: "createLanguage",
			Handler:    _Seppo_CreateLanguage_Handler,
		},
		{
			MethodName: "updateLanguage",
			Handler:    _Seppo_UpdateLanguage_Handler,
		},
		{
			MethodName: "removeLanguage",
			Handler:    _Seppo_RemoveLanguage_Handler,
		},
		{
			MethodName: "createSchedule",
			Handler:    _Seppo_CreateSchedule_Handler,
		},
		{
			MethodName: "updateSchedule",
			Handler:    _Seppo_UpdateSchedule_Handler,
		},
		{
			MethodName: "removeSchedule",
			Handler:    _Seppo_RemoveSchedule_Handler,
		},
		{
			MethodName: "createAuthor",
			Handler:    _Seppo_CreateAuthor_Handler,
		},
		{
			MethodName: "updateAuthor",
			Handler:    _Seppo_UpdateAuthor_Handler,
		},
		{
			MethodName: "removeAuthor",
			Handler:    _Seppo_RemoveAuthor_Handler,
		},
		{
			MethodName: "createCopyright",
			Handler:    _Seppo_CreateCopyright_Handler,
		},
		{
			MethodName: "updateCopyright",
			Handler:    _Seppo_UpdateCopyright_Handler,
		},
		{
			MethodName: "removeCopyright",
			Handler:    _Seppo_RemoveCopyright_Handler,
		},
		{
			MethodName: "updateMatiasClient",
			Handler:    _Seppo_UpdateMatiasClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seppo_service.proto",
}

func init() { proto.RegisterFile("seppo_service.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 958 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x98, 0xdf, 0x6a, 0x1b, 0x47,
	0x14, 0xc6, 0xeb, 0x8b, 0x16, 0x3c, 0xc8, 0x76, 0xbd, 0xa6, 0x94, 0x9a, 0x52, 0xb7, 0xfe, 0xab,
	0xb6, 0xa0, 0x52, 0xe7, 0x3a, 0x81, 0x58, 0x49, 0xc0, 0xe0, 0x18, 0xb2, 0xd2, 0xda, 0x10, 0x08,
	0xca, 0x58, 0x1a, 0xaf, 0x16, 0x64, 0xad, 0xb2, 0xb3, 0x92, 0xf0, 0x4d, 0x6e, 0xf3, 0x0e, 0x79,
	0x85, 0xbc, 0x64, 0xd0, 0xcc, 0xce, 0xe8, 0xcc, 0xce, 0x39, 0x23, 0x25, 0x77, 0xf1, 0x7e, 0xbf,
	0xfd, 0xbe, 0x39, 0x47, 0xb3, 0x73, 0x86, 0xb0, 0x3d, 0x29, 0x26, 0x93, 0xbc, 0x27, 0x45, 0x31,
	0xcb, 0xfa, 0xa2, 0x35, 0x29, 0xf2, 0x32, 0x8f, 0x1a, 0x9d, 0xc5, 0xc3, 0x8e, 0x7e, 0xb6, 0xbf,
	0x27, 0xf3, 0x71, 0xda, 0x1b, 0xf0, 0x92, 0xdf, 0x71, 0x59, 0x21, 0xfb, 0xbb, 0x62, 0x5e, 0x7f,
	0xb4, 0x25, 0xe6, 0xbd, 0x05, 0x5a, 0xfd, 0xb9, 0x59, 0x72, 0xf3, 0xcf, 0xed, 0x11, 0x1f, 0xa7,
	0x53, 0x9e, 0x1a, 0x72, 0x5b, 0xf6, 0x87, 0x62, 0x30, 0x1d, 0x99, 0xbf, 0x7f, 0x9d, 0xf1, 0x22,
	0xe3, 0x65, 0x96, 0x8f, 0x7b, 0x33, 0x51, 0xc8, 0x2c, 0x1f, 0x1b, 0x8f, 0x51, 0x6e, 0x3c, 0x76,
	0x2c, 0x53, 0x3d, 0x68, 0xf0, 0x69, 0x39, 0xcc, 0x0b, 0x23, 0xf7, 0xf3, 0xc9, 0x63, 0x91, 0xa5,
	0xc3, 0xb2, 0x7a, 0xb0, 0xf7, 0xc0, 0xcb, 0x8c, 0xcb, 0x5e, 0x7f, 0x94, 0x89, 0x71, 0xf5, 0xf0,
	0xfc, 0xf3, 0x09, 0xfb, 0x51, 0xd5, 0x16, 0x65, 0x2c, 0xba, 0x17, 0x65, 0x7f, 0x78, 0x63, 0x5c,
	0x2f, 0x1e, 0x2f, 0x07, 0xd1, 0x59, 0x0b, 0x56, 0xde, 0x7a, 0xe5, 0x11, 0xb1, 0xf8, 0x30, 0x15,
	0xb2, 0xdc, 0x6f, 0xae, 0x06, 0xe5, 0x24, 0x1f, 0x4b, 0x71, 0xf8, 0x43, 0xd4, 0x67, 0x3f, 0x4b,
	0xc1, 0x0b, 0x00, 0xc8, 0xe8, 0xc4, 0x7d, 0xbf, 0x53, 0xd3, 0x4d, 0xcc, 0xe9, 0x2a, 0xcc, 0x86,
	0x7c, 0xd9, 0x60, 0x4d, 0x55, 0xd0, 0xb5, 0x98, 0x0b, 0x59, 0x5a, 0xe6, 0x46, 0xf7, 0xf3, 0xe2,
	0xd1, 0x3e, 0xb9, 0x1c, 0x44, 0x4f, 0x91, 0xd5, 0xaf, 0xf1, 0x9e, 0x59, 0xd5, 0xb3, 0xef, 0x7d,
	0xdd, 0xae, 0xf6, 0x23, 0xfb, 0xcd, 0xed, 0xbe, 0xe5, 0x2f, 0x07, 0x51, 0x2b, 0xd4, 0x5b, 0x00,
	0x9a, 0xe5, 0xfc, 0xb7, 0x36, 0x6f, 0xf3, 0x47, 0x8b, 0x7d, 0xbf, 0xe8, 0x65, 0x27, 0x1f, 0xa7,
	0x2f, 0xaa, 0x6d, 0x2c, 0xa3, 0x26, 0xd6, 0x6e, 0x07, 0x31, 0x99, 0x7f, 0xaf, 0x41, 0xda, 0xb4,
	0x82, 0xfd, 0xa2, 0xaa, 0x85, 0xba, 0xaa, 0xf4, 0x1f, 0x64, 0xe5, 0x75, 0xc8, 0x24, 0xfe, 0xbb,
	0x16, 0x6b, 0x33, 0xef, 0xd9, 0xae, 0xae, 0xf0, 0xe5, 0x7c, 0x59, 0x1f, 0xba, 0x9d, 0x00, 0x60,
	0xb2, 0xce, 0x56, 0x72, 0xb0, 0x93, 0xaa, 0xb6, 0xa5, 0xaa, 0x2a, 0xc3, 0xbe, 0x0f, 0x17, 0x21,
	0x3a, 0x89, 0x92, 0x36, 0xed, 0x0d, 0x63, 0xba, 0xaa, 0x2e, 0x4f, 0x65, 0x74, 0x80, 0x2d, 0x73,
	0xa1, 0x18, 0xef, 0x3f, 0x69, 0xc0, 0x5a, 0xde, 0xb2, 0x86, 0x2a, 0xa0, 0xcb, 0x53, 0xb5, 0xf2,
	0xbf, 0x90, 0xf5, 0x54, 0x9a, 0xb1, 0x3d, 0x0c, 0x21, 0xd6, 0xf8, 0x3d, 0xdb, 0xd1, 0x6b, 0xbd,
	0xaa, 0x0e, 0x3f, 0x19, 0x1d, 0x63, 0xeb, 0xb1, 0xb2, 0xb1, 0x3f, 0x59, 0x41, 0xc1, 0xdf, 0x58,
	0x2d, 0xdd, 0x68, 0x6a, 0xfd, 0xa7, 0xc8, 0xe2, 0x20, 0x40, 0xfc, 0xc6, 0x08, 0xe7, 0x57, 0xd2,
	0xa9, 0x8e, 0x6d, 0xa2, 0x12, 0x2b, 0x07, 0x2b, 0x01, 0x94, 0x57, 0x89, 0xd1, 0xc8, 0x4a, 0x20,
	0x10, 0xaa, 0xc4, 0xe5, 0x6c, 0xce, 0x5b, 0xb6, 0xa5, 0x2b, 0x79, 0xae, 0x66, 0x87, 0x8c, 0x0e,
	0xb1, 0x15, 0x56, 0xa2, 0xf1, 0x3f, 0x0a, 0x32, 0xb0, 0x4b, 0xaa, 0x06, 0xad, 0xa8, 0x0a, 0x8e,
	0x91, 0x95, 0x2d, 0x65, 0xa2, 0x4b, 0x1e, 0xe5, 0x0f, 0x92, 0xb6, 0x99, 0x75, 0xc4, 0x20, 0x59,
	0xea, 0xc1, 0x41, 0x02, 0x31, 0x1b, 0x62, 0x06, 0xa3, 0x15, 0xc9, 0xc1, 0xe8, 0x10, 0xa1, 0xc1,
	0x58, 0x03, 0xfd, 0x53, 0xf8, 0xb5, 0x1a, 0xd5, 0x6d, 0x35, 0xa9, 0x89, 0x53, 0xd8, 0x41, 0x82,
	0xa7, 0x70, 0x8d, 0xf4, 0xf6, 0x18, 0xd4, 0xd1, 0x3d, 0x06, 0x81, 0xd0, 0x1e, 0x73, 0x39, 0x9b,
	0xf3, 0x69, 0x83, 0xfd, 0xee, 0x05, 0xc1, 0x53, 0xf8, 0xff, 0x15, 0x5e, 0xc8, 0x81, 0x7c, 0xfe,
	0x2d, 0xaf, 0xf8, 0xa7, 0xe5, 0x55, 0x4e, 0x9d, 0x96, 0x0b, 0x25, 0x78, 0x5a, 0x6a, 0x00, 0x6e,
	0xf2, 0x7e, 0x21, 0x78, 0x29, 0xec, 0x80, 0xad, 0x6f, 0xf2, 0xb6, 0x2b, 0x13, 0x9b, 0xdc, 0xa3,
	0x60, 0xc2, 0x74, 0x32, 0x08, 0x25, 0x24, 0xae, 0x4c, 0x24, 0x78, 0x14, 0x4c, 0x28, 0xc4, 0x43,
	0x3e, 0xa3, 0x13, 0x62, 0x57, 0x26, 0x12, 0x3c, 0x0a, 0x7e, 0x43, 0xba, 0x4b, 0x70, 0x40, 0xd7,
	0xbf, 0xa1, 0xb6, 0x47, 0x10, 0xdf, 0x10, 0x06, 0xc2, 0x28, 0xdd, 0xae, 0x50, 0x54, 0xe2, 0x11,
	0x44, 0x14, 0x06, 0xc2, 0x28, 0xdd, 0xb7, 0x50, 0x54, 0xec, 0x11, 0x44, 0x14, 0x06, 0xc2, 0x93,
	0x4e, 0x37, 0x70, 0xb9, 0xb1, 0x23, 0x74, 0x07, 0x2d, 0x75, 0xe2, 0xa4, 0xf3, 0x31, 0x18, 0xa2,
	0x5b, 0x47, 0x87, 0x24, 0x35, 0x9d, 0x08, 0xf1, 0x31, 0x18, 0xa2, 0x9b, 0x46, 0x87, 0xc4, 0x35,
	0x9d, 0x08, 0xf1, 0x31, 0x1b, 0x72, 0xcd, 0x36, 0x75, 0xbb, 0xba, 0x3c, 0x8d, 0xfe, 0xc0, 0x1a,
	0xd0, 0xe5, 0xa9, 0xb1, 0x3d, 0x20, 0x75, 0xe8, 0xa7, 0x3b, 0x83, 0xf8, 0x25, 0x46, 0x20, 0xfc,
	0x80, 0x0e, 0xfd, 0x74, 0x13, 0x10, 0xbf, 0xd8, 0x08, 0x84, 0x1f, 0xd0, 0xad, 0xdf, 0x3b, 0xb6,
	0xad, 0xeb, 0x35, 0x17, 0x96, 0xe8, 0x08, 0x2b, 0xca, 0xa8, 0xc6, 0xf9, 0x38, 0x0c, 0x41, 0x7b,
	0x5d, 0x3e, 0x65, 0x9f, 0x38, 0x2a, 0x61, 0x5f, 0x87, 0xa0, 0xbd, 0xee, 0x06, 0x65, 0x1f, 0x3b,
	0x2a, 0x61, 0x5f, 0x87, 0xfc, 0xe6, 0x98, 0x3b, 0x10, 0xde, 0x1c, 0xa3, 0x06, 0x9b, 0xb3, 0x84,
	0xfc, 0xe6, 0x50, 0xf6, 0x89, 0xa3, 0x06, 0x9b, 0x83, 0xdb, 0x57, 0x87, 0x0c, 0x61, 0x1f, 0x3b,
	0x6a, 0xb0, 0x39, 0x88, 0xfd, 0x2d, 0x6b, 0xe8, 0xe6, 0xe8, 0x0b, 0x56, 0xfd, 0xb6, 0xdf, 0x06,
	0x1a, 0x71, 0xdb, 0x77, 0x11, 0x68, 0xac, 0xdb, 0x82, 0x1b, 0x27, 0x40, 0x23, 0x8c, 0x5d, 0x04,
	0x1a, 0xeb, 0x86, 0xe0, 0xc6, 0x31, 0xd0, 0x08, 0x63, 0x17, 0xf1, 0x47, 0xb9, 0xbd, 0x9e, 0xe1,
	0xa3, 0xdc, 0xca, 0xc1, 0x51, 0x0e, 0x28, 0x7f, 0x94, 0x93, 0x09, 0x89, 0x2b, 0x07, 0x47, 0x39,
	0x91, 0xa0, 0x9b, 0x43, 0x26, 0xc4, 0xae, 0x1c, 0x1c, 0xe5, 0x58, 0x82, 0x9d, 0xaf, 0xce, 0xb5,
	0x11, 0x9d, 0xaf, 0xd8, 0xbd, 0xb1, 0xb9, 0x1a, 0x34, 0x51, 0x77, 0x3f, 0xa9, 0xff, 0xa3, 0x7a,
	0xf2, 0x35, 0x00, 0x00, 0xff, 0xff, 0x37, 0x52, 0xf1, 0xfe, 0x93, 0x13, 0x00, 0x00,
}
