// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package RistoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateTokenResponse_State int32

const (
	CreateTokenResponse_TOKEN_CREATED  CreateTokenResponse_State = 0
	CreateTokenResponse_USER_NOT_FOUND CreateTokenResponse_State = 1
	CreateTokenResponse_PASSWORD_WRONG CreateTokenResponse_State = 2
)

var CreateTokenResponse_State_name = map[int32]string{
	0: "TOKEN_CREATED",
	1: "USER_NOT_FOUND",
	2: "PASSWORD_WRONG",
}
var CreateTokenResponse_State_value = map[string]int32{
	"TOKEN_CREATED":  0,
	"USER_NOT_FOUND": 1,
	"PASSWORD_WRONG": 2,
}

func (x CreateTokenResponse_State) String() string {
	return proto.EnumName(CreateTokenResponse_State_name, int32(x))
}
func (CreateTokenResponse_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type VerifyTokenResponse_State int32

const (
	VerifyTokenResponse_VERIFIED VerifyTokenResponse_State = 0
	VerifyTokenResponse_EXPIRED  VerifyTokenResponse_State = 1
	VerifyTokenResponse_INVALID  VerifyTokenResponse_State = 3
)

var VerifyTokenResponse_State_name = map[int32]string{
	0: "VERIFIED",
	1: "EXPIRED",
	3: "INVALID",
}
var VerifyTokenResponse_State_value = map[string]int32{
	"VERIFIED": 0,
	"EXPIRED":  1,
	"INVALID":  3,
}

func (x VerifyTokenResponse_State) String() string {
	return proto.EnumName(VerifyTokenResponse_State_name, int32(x))
}
func (VerifyTokenResponse_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4, 0} }

type Token struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateTokenRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	MaxAge     uint64 `protobuf:"varint,3,opt,name=maxAge" json:"maxAge,omitempty"`
	RememberMe bool   `protobuf:"varint,4,opt,name=rememberMe" json:"rememberMe,omitempty"`
}

func (m *CreateTokenRequest) Reset()                    { *m = CreateTokenRequest{} }
func (m *CreateTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTokenRequest) ProtoMessage()               {}
func (*CreateTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CreateTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateTokenRequest) GetMaxAge() uint64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *CreateTokenRequest) GetRememberMe() bool {
	if m != nil {
		return m.RememberMe
	}
	return false
}

type CreateTokenResponse struct {
	Token string                    `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	State CreateTokenResponse_State `protobuf:"varint,2,opt,name=state,enum=RistoService.CreateTokenResponse_State" json:"state,omitempty"`
	User  *User                     `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *CreateTokenResponse) Reset()                    { *m = CreateTokenResponse{} }
func (m *CreateTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTokenResponse) ProtoMessage()               {}
func (*CreateTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CreateTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateTokenResponse) GetState() CreateTokenResponse_State {
	if m != nil {
		return m.State
	}
	return CreateTokenResponse_TOKEN_CREATED
}

func (m *CreateTokenResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type VerifyTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *VerifyTokenRequest) Reset()                    { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()               {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *VerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResponse struct {
}

func (m *VerifyTokenResponse) Reset()                    { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()               {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type FetchUserByTokenRequest struct {
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *FetchUserByTokenRequest) Reset()                    { *m = FetchUserByTokenRequest{} }
func (m *FetchUserByTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchUserByTokenRequest) ProtoMessage()               {}
func (*FetchUserByTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *FetchUserByTokenRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type FetchUserByTokenResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *FetchUserByTokenResponse) Reset()                    { *m = FetchUserByTokenResponse{} }
func (m *FetchUserByTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchUserByTokenResponse) ProtoMessage()               {}
func (*FetchUserByTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *FetchUserByTokenResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "RistoService.Token")
	proto.RegisterType((*CreateTokenRequest)(nil), "RistoService.CreateTokenRequest")
	proto.RegisterType((*CreateTokenResponse)(nil), "RistoService.CreateTokenResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "RistoService.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "RistoService.VerifyTokenResponse")
	proto.RegisterType((*FetchUserByTokenRequest)(nil), "RistoService.FetchUserByTokenRequest")
	proto.RegisterType((*FetchUserByTokenResponse)(nil), "RistoService.FetchUserByTokenResponse")
	proto.RegisterEnum("RistoService.CreateTokenResponse_State", CreateTokenResponse_State_name, CreateTokenResponse_State_value)
	proto.RegisterEnum("RistoService.VerifyTokenResponse_State", VerifyTokenResponse_State_name, VerifyTokenResponse_State_value)
}

func init() { proto.RegisterFile("token.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0xaf, 0xd2, 0x40,
	0x14, 0x75, 0xde, 0xa3, 0xef, 0xe1, 0x2d, 0xbe, 0xd4, 0xc1, 0x68, 0x43, 0xa2, 0x21, 0x5d, 0x28,
	0x71, 0x51, 0x12, 0x5c, 0xbb, 0x28, 0xb4, 0x35, 0x8d, 0xda, 0x92, 0x69, 0x01, 0x77, 0x4d, 0xc1,
	0xab, 0x12, 0x53, 0x8a, 0x33, 0x83, 0x1f, 0x7b, 0x7f, 0xa3, 0xbf, 0xc7, 0xcc, 0x94, 0x1a, 0x1a,
	0x09, 0xcb, 0x33, 0xe7, 0x9c, 0x39, 0xe7, 0xde, 0x19, 0x30, 0x65, 0xf5, 0x15, 0x77, 0xee, 0x9e,
	0x57, 0xb2, 0xa2, 0x3d, 0xb6, 0x15, 0xb2, 0x4a, 0x91, 0x7f, 0xdf, 0x6e, 0x70, 0x00, 0x07, 0x81,
	0xbc, 0x66, 0x9c, 0xa7, 0x60, 0x64, 0x4a, 0x48, 0x1f, 0x81, 0xa1, 0x1d, 0x36, 0x19, 0x92, 0xd1,
	0x7d, 0x56, 0x03, 0xe7, 0x37, 0x01, 0x3a, 0xe3, 0x58, 0x48, 0xd4, 0x2a, 0x86, 0xdf, 0x0e, 0x28,
	0x24, 0x1d, 0x40, 0x57, 0xdd, 0xb1, 0x2b, 0x4a, 0x3c, 0xea, 0xff, 0x61, 0xc5, 0xed, 0x0b, 0x21,
	0x7e, 0x54, 0xfc, 0xa3, 0x7d, 0x55, 0x73, 0x0d, 0xa6, 0x8f, 0xe1, 0xa6, 0x2c, 0x7e, 0x7a, 0x9f,
	0xd1, 0xbe, 0x1e, 0x92, 0x51, 0x87, 0x1d, 0x11, 0x7d, 0x06, 0xc0, 0xb1, 0xc4, 0x72, 0x8d, 0xfc,
	0x3d, 0xda, 0x9d, 0x21, 0x19, 0x75, 0xd9, 0xc9, 0x89, 0xf3, 0x87, 0x40, 0xbf, 0x55, 0x43, 0xec,
	0xab, 0x9d, 0xc0, 0xf3, 0xa5, 0xe9, 0x6b, 0x30, 0x84, 0x2c, 0x24, 0xea, 0xf8, 0xbb, 0xc9, 0x0b,
	0xf7, 0x74, 0x7a, 0xf7, 0xcc, 0x3d, 0x6e, 0xaa, 0xe4, 0xac, 0x76, 0xd1, 0xe7, 0xd0, 0x51, 0xc3,
	0xe8, 0x8a, 0xe6, 0x84, 0xb6, 0xdd, 0x0b, 0x81, 0x9c, 0x69, 0xde, 0x99, 0x82, 0xa1, 0x7d, 0xf4,
	0x21, 0x3c, 0xc8, 0x92, 0xb7, 0x41, 0x9c, 0xcf, 0x58, 0xe0, 0x65, 0x81, 0x6f, 0xdd, 0xa3, 0x14,
	0xee, 0x16, 0x69, 0xc0, 0xf2, 0x38, 0xc9, 0xf2, 0x30, 0x59, 0xc4, 0xbe, 0x45, 0xd4, 0xd9, 0xdc,
	0x4b, 0xd3, 0x55, 0xc2, 0xfc, 0x7c, 0xc5, 0x92, 0xf8, 0x8d, 0x75, 0xe5, 0xbc, 0x04, 0xba, 0x44,
	0xbe, 0xfd, 0xf4, 0xab, 0xb5, 0xde, 0xf3, 0x6f, 0x11, 0x42, 0xbf, 0xa5, 0xad, 0xbb, 0x3b, 0xe3,
	0xa6, 0x46, 0x0f, 0xba, 0xcb, 0x80, 0x45, 0x61, 0xa4, 0x1b, 0x98, 0x70, 0x1b, 0x7c, 0x98, 0x47,
	0x2c, 0x50, 0xd1, 0x26, 0xdc, 0x46, 0xf1, 0xd2, 0x7b, 0x17, 0xf9, 0xd6, 0xb5, 0x33, 0x86, 0x27,
	0x21, 0xca, 0xcd, 0x17, 0x35, 0xca, 0xf4, 0x42, 0x70, 0xaf, 0x09, 0x9e, 0x82, 0xfd, 0xbf, 0xe1,
	0xf8, 0x02, 0xcd, 0xb2, 0xc8, 0xe5, 0x65, 0xad, 0x6f, 0xf4, 0x77, 0x7b, 0xf5, 0x37, 0x00, 0x00,
	0xff, 0xff, 0xdd, 0x5a, 0xce, 0x1a, 0x97, 0x02, 0x00, 0x00,
}
