// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package RistoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type User struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	IsAdmin  bool   `protobuf:"varint,3,opt,name=isAdmin" json:"isAdmin,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type CreateUserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type HasAdminAccountRequest struct {
}

func (m *HasAdminAccountRequest) Reset()                    { *m = HasAdminAccountRequest{} }
func (m *HasAdminAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*HasAdminAccountRequest) ProtoMessage()               {}
func (*HasAdminAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type HasAdminAccountResponse struct {
	HasAdminAccount bool `protobuf:"varint,1,opt,name=hasAdminAccount" json:"hasAdminAccount,omitempty"`
}

func (m *HasAdminAccountResponse) Reset()                    { *m = HasAdminAccountResponse{} }
func (m *HasAdminAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*HasAdminAccountResponse) ProtoMessage()               {}
func (*HasAdminAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *HasAdminAccountResponse) GetHasAdminAccount() bool {
	if m != nil {
		return m.HasAdminAccount
	}
	return false
}

type CreateAdminAccountRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *CreateAdminAccountRequest) Reset()                    { *m = CreateAdminAccountRequest{} }
func (m *CreateAdminAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAdminAccountRequest) ProtoMessage()               {}
func (*CreateAdminAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *CreateAdminAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateAdminAccountResponse struct {
	User    *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *CreateAdminAccountResponse) Reset()                    { *m = CreateAdminAccountResponse{} }
func (m *CreateAdminAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAdminAccountResponse) ProtoMessage()               {}
func (*CreateAdminAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *CreateAdminAccountResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAdminAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "RistoService.User")
	proto.RegisterType((*CreateUserRequest)(nil), "RistoService.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "RistoService.CreateUserResponse")
	proto.RegisterType((*HasAdminAccountRequest)(nil), "RistoService.HasAdminAccountRequest")
	proto.RegisterType((*HasAdminAccountResponse)(nil), "RistoService.HasAdminAccountResponse")
	proto.RegisterType((*CreateAdminAccountRequest)(nil), "RistoService.CreateAdminAccountRequest")
	proto.RegisterType((*CreateAdminAccountResponse)(nil), "RistoService.CreateAdminAccountResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x10, 0x41, 0x38, 0x10, 0x08, 0x0f, 0x60, 0x3a, 0x45, 0x1e, 0x50, 0xa6, 0x0c,
	0x30, 0xb0, 0xb0, 0x54, 0x5d, 0x90, 0x40, 0x0c, 0x46, 0xac, 0x48, 0xc1, 0x39, 0x09, 0x0f, 0x8d,
	0x83, 0xcf, 0x86, 0xbf, 0x8f, 0xec, 0xd6, 0xd0, 0x96, 0x2c, 0x8c, 0x2f, 0x2f, 0xf7, 0xdd, 0x7b,
	0x3e, 0x80, 0x40, 0xe8, 0xda, 0xd1, 0x59, 0x6f, 0xf9, 0xb1, 0x32, 0xe4, 0xed, 0x33, 0xba, 0x4f,
	0xa3, 0x51, 0x3e, 0x42, 0xf9, 0x42, 0xe8, 0xf8, 0x09, 0x14, 0xa6, 0x17, 0xac, 0x66, 0x4d, 0xa9,
	0x0a, 0xd3, 0xf3, 0x19, 0x54, 0x71, 0xe6, 0xa9, 0x5b, 0xa2, 0x28, 0x6a, 0xd6, 0x1c, 0xaa, 0x1f,
	0xcd, 0x05, 0x1c, 0x18, 0x9a, 0xf7, 0x4b, 0x33, 0x88, 0xbd, 0x9a, 0x35, 0x95, 0xca, 0x52, 0x3e,
	0xc0, 0xd9, 0xc2, 0x61, 0xe7, 0x31, 0x32, 0x15, 0x7e, 0x04, 0x24, 0x9f, 0x51, 0x43, 0x44, 0xb1,
	0x5f, 0x54, 0xd4, 0xd1, 0x1b, 0x3b, 0xa2, 0x2f, 0xeb, 0xfa, 0xbc, 0x26, 0x6b, 0x79, 0x07, 0x7c,
	0x13, 0x46, 0xa3, 0x1d, 0x08, 0xf9, 0x15, 0x94, 0x71, 0x3a, 0x91, 0x8e, 0xae, 0x79, 0xbb, 0xd9,
	0xa6, 0x4d, 0x7f, 0x26, 0x5f, 0x0a, 0x38, 0xbf, 0xef, 0x56, 0xb1, 0xe6, 0x5a, 0xdb, 0x30, 0xf8,
	0x75, 0x1e, 0xb9, 0x80, 0x8b, 0x3f, 0xce, 0x1a, 0xde, 0xc0, 0xe9, 0xfb, 0xb6, 0x95, 0xf6, 0x54,
	0x6a, 0xf7, 0xb3, 0xbc, 0x85, 0xcb, 0x55, 0xb8, 0x89, 0x0d, 0x5b, 0xad, 0xd8, 0x4e, 0xab, 0x57,
	0x98, 0x4d, 0x0d, 0xfe, 0xaf, 0x5d, 0x3c, 0x01, 0x05, 0xad, 0x91, 0x28, 0x3d, 0x5b, 0xa5, 0xb2,
	0x7c, 0xdb, 0x4f, 0x57, 0xbe, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x89, 0x78, 0x6e, 0x13, 0xf3,
	0x01, 0x00, 0x00,
}
